apiVersion: storage.example.com/v1alpha1
kind: CloudBucket
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudbucket-sample
spec:
  bucketName: elton-demo-bucket-123
  provider: minio
  region: us-south
  credentialsSecretName: cloudbucket-credentials
