apiVersion: v1
kind: Secret
metadata:
  name: cloudbucket-ibm-credentials
type: Opaque
stringData:
  apiKey: "REPLACE_WITH_IBM_CLOUD_API_KEY"
  resourceInstanceID: "REPLACE_WITH_COS_RESOURCE_INSTANCE_CRN"
  region: "us-south"
